// Generated by https://quicktype.io

export interface IContacto {
    id:         number;
    attributes: IContactoAttributes;
}

export interface IContactoAttributes {
    nombre:          string;
    email:           string;
    LaRioja:         boolean;
    createdAt:       string;
    updatedAt:       string;
    publishedAt:     string;
}