// Generated by https://quicktype.io

import { IUser } from "./auth.interfaces";
import { ICategoria } from "./categorias.interfaces";
import { IListaContacto } from "./listaContactos.interfaces";

export interface IContacto {
    id:         number;
    attributes: IContactoAttributes;
}

export interface IContactoAttributes {
    nombre:          string;
    email:           string;
    LaRioja:         boolean;
    createdAt:       string;
    updatedAt:       string;
    publishedAt:     string;
    usuario: {
        data: IUser
    },
    lista_contactos?: {
        data: IListaContacto[]
    };
    categorias?: {
        data: ICategoria[]
    }
}

export interface IFormNuevoContacto {
    nombre: string;
    email: string;
}